language: java

env:
 - ANDROID_HOME=~/builds/androrm/androrm/android-sdk-linux

before_install:
 - wget http://dl.google.com/android/android-sdk_r20.0.3-linux.tgz
 - tar -zxf android-sdk_r20.0.3-linux.tgz
 - android update sdk --filter 1,2,9 --no-ui --force
